server:
  port: 8088

druid:
    url: jdbc:mysql://127.0.0.1:3306/second_kill
    username: root
    password: luohui
    initial-size: 1
    min-idle: 1
    max-active: 20
    test-on-borrow: true

spring:
    mvc:
        view:
            prefix: /templates/
            suffix: .html
    freemarker:
        cache: false
        request-context-attribute: request


mybatis:
    type-aliases-package: com.xcalculas.study.domain
    mapper-locations: classpath:mapper/*.xml
    configuration:
      use-column-label: true

mapper:
    mappers:
        - com.xcalculas.study.utils.MyMapper
    not-empty: false
    identity: MYSQL


pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

logging:
  level:
    root: info
    org.springframework.web: info
    com.xcalculas: debug
