package com.xcalculas.study.domain;

import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import java.util.Date;

public class SecondKill {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_kill.seckill_id
     *
     * @mbggenerated Mon Mar 20 20:51:08 CST 2017
     */
    @Id
    @Column(name = "seckill_id")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private String seckillId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_kill.name
     *
     * @mbggenerated Mon Mar 20 20:51:08 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_kill.number
     *
     * @mbggenerated Mon Mar 20 20:51:08 CST 2017
     */
    private Integer number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_kill.create_time
     *
     * @mbggenerated Mon Mar 20 20:51:08 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_kill.start_time
     *
     * @mbggenerated Mon Mar 20 20:51:08 CST 2017
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_kill.end_time
     *
     * @mbggenerated Mon Mar 20 20:51:08 CST 2017
     */
    private Date endTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_kill.seckill_id
     *
     * @return the value of second_kill.seckill_id
     *
     * @mbggenerated Mon Mar 20 20:51:08 CST 2017
     */
    public String getSeckillId() {
        return seckillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_kill.seckill_id
     *
     * @param seckillId the value for second_kill.seckill_id
     *
     * @mbggenerated Mon Mar 20 20:51:08 CST 2017
     */
    public void setSeckillId(String seckillId) {
        this.seckillId = seckillId == null ? null : seckillId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_kill.name
     *
     * @return the value of second_kill.name
     *
     * @mbggenerated Mon Mar 20 20:51:08 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_kill.name
     *
     * @param name the value for second_kill.name
     *
     * @mbggenerated Mon Mar 20 20:51:08 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_kill.number
     *
     * @return the value of second_kill.number
     *
     * @mbggenerated Mon Mar 20 20:51:08 CST 2017
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_kill.number
     *
     * @param number the value for second_kill.number
     *
     * @mbggenerated Mon Mar 20 20:51:08 CST 2017
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_kill.create_time
     *
     * @return the value of second_kill.create_time
     *
     * @mbggenerated Mon Mar 20 20:51:08 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_kill.create_time
     *
     * @param createTime the value for second_kill.create_time
     *
     * @mbggenerated Mon Mar 20 20:51:08 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_kill.start_time
     *
     * @return the value of second_kill.start_time
     *
     * @mbggenerated Mon Mar 20 20:51:08 CST 2017
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_kill.start_time
     *
     * @param startTime the value for second_kill.start_time
     *
     * @mbggenerated Mon Mar 20 20:51:08 CST 2017
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_kill.end_time
     *
     * @return the value of second_kill.end_time
     *
     * @mbggenerated Mon Mar 20 20:51:08 CST 2017
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_kill.end_time
     *
     * @param endTime the value for second_kill.end_time
     *
     * @mbggenerated Mon Mar 20 20:51:08 CST 2017
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    @Override
    public String toString() {
        return "SecondKill{" +
                "seckillId='" + seckillId + '\'' +
                ", name='" + name + '\'' +
                ", number=" + number +
                ", createTime=" + createTime +
                ", startTime=" + startTime +
                ", endTime=" + endTime +
                '}';
    }
}